### ISSUE TITLE
Mobile support

### ISSUE THREAD

**Issue by jamierocks** [SpongePowered/SpongeHome#11]
![image](https://cloud.githubusercontent.com/assets/5103549/14403100/bfdb2f26-fe42-11e5-911f-340295fed393.png)

I experimented around and the following should work.

``` scss
// iPhone 4/4s to iPhone 6
@media only screen
and (min-device-width: 320px)
and (max-device-width: 667px)
and (-webkit-min-device-pixel-ratio: 2) {
    .col-xs-2 {
        width: 100%;
    }
    .col-xs-offset-1 {
        margin-left: 0;
    }
}

// iPhone 6+
@media only screen
and (min-device-width: 414px)
and (max-device-width: 736px)
and (-webkit-min-device-pixel-ratio: 3) {
    .col-xs-2 {
        width: 100%;
    }
    .col-xs-offset-1 {
        margin-left: 0;
    }
}
```

With those changes in place you get: ![image](https://i.lexteam.xyz/Kk0gtpD7T8.png)
