### ISSUE TITLE
Main logo is sized oddly

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeHome#68]
The issue is mainly with Safari on Mac OS X:

![safari](http://puu.sh/oEtbB/767ee75aaa.png)

Versus Chrome:
![chrome](http://puu.sh/oEtbY/0bc10638cc.png)

**Comment by windy1** [comment]
This seems to be specific to Safari.

**Comment by Tzky** [comment]
We had this issue with Firefox too, however @jamierocks managed to fix it.

**Comment by jamierocks** [comment]
@tzky tgis is worse than the first issue - thinking I might know why it's happening though

**Comment by windy1** [comment]
@jamierocks 

Here's a fix that should work for you:

``` css
#main-display {
  padding-top: 15%;
  display: table;
  padding: 1em 1em 2em;
  width: 74%
  img { float: left; }
  img, .intro-text {
    display: table-cell;
    vertical-align: middle;
  }
}
```
